spring.application.name=axon-saga-module

#### MySQL ####
spring.datasource.url=jdbc:mysql://localhost:3306/axon?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
spring.datasource.username=root
spring.datasource.password=root

#### Spring Data JPA ####
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#### Axon ####
axon.eventhandling.processors.order-group.mode=tracking
axon.eventhandling.processors.order-group.initial-segment-count=1
axon.axonserver.servers=127.0.0.1:8124
axon.axonserver.context=default
axon.axonserver.component-name=order-service

# 強制 Axon 使用 jackson 處理所有序列化
axon.serializer.general=jackson
axon.serializer.messages=jackson
axon.serializer.events=jackson
